#!/bin/sh

NAME="${1:-website}"

echo "## Opening a shell in the container running service ${NAME}_app"

# Find the container ID searching for the service name
# From: https://stackoverflow.com/a/52005021
ID=$(docker ps -q -f name="${NAME}_app")

# Move to the docker exec shell
docker exec -it "$ID" sh
