#!/bin/sh

SCRIPT_NAME=$(basename "$0")
usage () {
  printf "%s\n\n" "Usage: $SCRIPT_NAME [OPTIONS]"
  printf "%s\n\nOptions:\n" "Create a link to live Let's Encrypt certificate \
files of a domain (suitable for static NGINX configuration files)."
  echo "  -h, --help    Show this message and exit"
  echo "  -d, --domain  Required: Link files for this domain"
  echo "  -p, --path    Location containing the Let's Encrypt folder"
  exit 0
}

# Process received parameters with getopt (available in BusyBox)
# https://busybox.net/downloads/BusyBox.html#getopt
O=$(getopt \
  -l domain: \
  -l path: \
  -l help \
  -- d:ph "$@" \
) || exit 1
eval set -- "$O"
while true; do
  case "$1" in
  -d|--domain) DOMAIN="$2"; shift 2;;
  -p|--path) DATA_PATH="$2"; shift 2;;
  -h|--help) usage; shift;;
  --) shift; break;;
  *) echo "## Error." >&2; exit 1;;
  esac
done

# Check if a domain was provided
if [ -z "${DOMAIN:+unsetornull}" ]; then
  echo "## Error: Provide a domain (using -d or --domain=)." >&2
  exit 1
fi

# Apply the default to DATA_PATH
cd $(dirname "$0")
CONF_CERTBOT="${DATA_PATH:-$(pwd)}/letsencrypt"

# Create (or update) links to the live certificate files
rm "${CONF_CERTBOT}/fullchain.pem" "${CONF_CERTBOT}/privkey.pem"
ln -s "./live/${DOMAIN}/fullchain.pem" "${CONF_CERTBOT}/fullchain.pem"
ln -s "./live/${DOMAIN}/privkey.pem" "${CONF_CERTBOT}/privkey.pem"
