version: "3.7"

networks:
  app:
    driver: overlay
    attachable: false

services:
  # HTTPS server that routes PHP calls to app:9000
  nginx:
    image: nginx:alpine
    networks:
      - app
    ports:
      - target: 80
        published: "${NGINX_HTTP_PORT:-80}"
        protocol: tcp
        mode: host
      - target: 443
        published: "${NGINX_HTTPS_PORT:-443}"
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./nginx/php-fpm.conf
        target: /etc/nginx/php-fpm.conf
        read_only: true
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./letsencrypt
        target: /etc/letsencrypt
        read_only: true
      - type: bind
        source: ./acme
        target: /var/www/acme
      - type: bind
        source: "${APP_ROOT:-./}"
        target: /var/www/html

  # Key-value data store for caching and pub/sub
  redis:
    image: redis:alpine
    networks:
      - app

  # PHP-FPM server that listens on app:9000
  app:
    image: matheusb-comp/php-laravel
    networks:
      - app
    environment:
      - "DB_CONNECTION=${DB_CONNECTION:-pgsql}"
      - "DB_PORT=${DB_PORT:-5432}"
      - "DB_HOST=${DB_HOST}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DATABASE_URL=${DATABASE_URL}"
      - "WAIT_DATABASE=true"
    volumes:
      - type: bind
        source: ./supervisor
        target: /etc/supervisor/conf.d
        read_only: true
      - type: bind
        source: "${APP_ROOT:-./}"
        target: /var/www/html
