#!/bin/sh

# Move to the script directory
cd $(dirname "$0")

if [ -e "${APP_ROOT:-..}/.env" ]; then
  echo "## Exporting variables from .env"
  # Export all .env variables
  # From: https://stackoverflow.com/a/30969768
  set -o allexport
  # Dot is the POSIX standard for the bash 'source'
  # http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#dot
  . "${APP_ROOT:-..}/.env"
  set +o allexport
fi

# Init the Docker swarm (silently ignore error messages)
docker swarm init > /dev/null 2>&1

NAME="${1:-website}"
STACK="${2:-stack}"
echo "## Starting stack ${NAME} using configuration file ${STACK}.yml"
# Also set the user and group numeric IDs for the database, and deploy the stack
env USER_ID=$(id -u) USER_GROUP=$(id -g) \
  docker stack deploy -c "./${STACK}.yml" "$NAME"
